name: Deploy Ember App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # 🚫 Remove or comment out this line if you have it
      # - name: Run Lint
      #   run: npm run lint

      - name: Build app
        run: npm run build --environment=production

      - name: Deploy to GitHub Pages
        run: npx ember github-pages:commit --branch=gh-pages --message "Initial deploy to GitHub Pages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
